### PR TITLE
asset detail page

### PR DESCRIPTION
**Pull request by ethan-57blocks**
added asset detail page

### CODE REVIEW

**Comment by allenchuang** [comment]
Screenshot 2024-02-01 at 2 56 23 PM
Hey @ethan-57blocks , this is not very aligned to match the Figma, can you please address?

Also we have an updated version for the "Tags" and cards that should scroll horizontally should there be more than 2 cards.
image


Let me know if you have any questions

**Comment by ethan-57blocks** [comment]
> Screenshot 2024-02-01 at 2 56 23 PM Hey @ethan-57blocks , this is not very aligned to match the Figma, can you please address?
> Also we have an updated version for the "Tags" and cards that should scroll horizontally should there be more than 2 cards. image
> 
> Let me know if you have any questions

@allenchuang  It currently looks like below, please review. Thanks so much!
image

**Comment by ethan-57blocks** [comment]
iPad pro:
image

iPad air:
image

iPad mini: 
image
image

iPhone 14pro max:
image
image

iPhone 12pro:
image
image

iPhone se:
image
image
image

**Comment by allenchuang** [comment]
302153980-4b15b465-65cf-46ef-a582-1a88be07de9c
302154652-5e7ec72f-463f-4ab6-86cc-77e89f7de0a6
302154828-957e9bce-b3f3-4df1-9eb1-6ee8b0793aac

Please make the Story logo just appear on a "top" nav, and remove the side navbar. The rest of the content should be below the topnav and the Story logo should appear on mobile as well

image

**Comment by allenchuang** [comment]
Also the content should be centered on large screen devices

**Comment by allenchuang** [comment]
- We need to parse the metadata, and retrieve image through mediaUrl 
- Please also update the `/ipa` and `/ipa/[ipOrgId]/[ipAssetId]`  pages on the dashboard to support this.
- please refer to `@/components/cards/AssetCard.tsx` and modify the code to support this
- please take into account for mediaURL beginning in `ipfs://`  or `ar://` we should use an gateway to resolve them
i,.e. `ipfs://bafkreibibneembl2hv2itxusv56r7jl3osyvd6go25z7ygylcwimtllavu` ->  `https://cloudflare-ipfs.com/ipfs/bafkreibibneembl2hv2itxusv56r7jl3osyvd6go25z7ygylcwimtllavu`

**Comment by allenchuang** [comment]
For Arweave use `https://arweave.net/`
For IPFS use `gateway.ipfs.io/ipfs/`

**Review by allenchuang — APPROVED** [review]
LGTM

**Pull request merged**
